# This workflow installs tSQLt and runs the test units

name: tSQLt installer and unit testing runner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-auth-tsqlt:
    name: Installting tSQLt with SQL Auth
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 3uuiCaKxfbForrK

    steps:
      - uses: actions/checkout@v2

      - name: Install tSQLt with SQL auth
        uses: lowlydba/tsqlt-installer@v1
        with:
          sql-instance: localhost
          database: master
          version: latest
          user: sa
          password: 3uuiCaKxfbForrK
        id: ItSQLt
        
      - name: Get the container ID
        run: echo "The container ID is ${{ steps.ItSQLt.outputs.imageid }}"
      
      - name: Gest the containers list
        run:
          docker ps
